steps:
  - name: 'gcr.io/cloud-builders/npm'
    args: ['install']  # Install npm dependencies
  - name: 'gcr.io/cloud-builders/npm'
    args: ['run', 'build']  # Build your app
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy', '--quiet', '--stop-previous-version']  # Deploy to App Engine and stop previous version
timeout: '900s'  # Optional: set a timeout for the build

options:
  logging: CLOUD_LOGGING_ONLY
  default_logs_bucket_behavior: REGIONAL_USER_OWNED_BUCKET
